version: "3.8"

services:
  app:
    image: ulilamry/belajarki:latest
    container_name: belajarki-app
    restart: always
    env_file: ../.env
    volumes:
      - web-static:/var/www/public
    networks:
      - belajarki-network

  web:
    image: nginx:alpine
    container_name: belajarki-nginx
    restart: always
    ports:
      - "80:80"
      - "443:443" # <--- BARU: Buka port HTTPS
    volumes:
      - web-static:/var/www/public
      - ./nginx/conf.d/:/etc/nginx/conf.d/
      - certbot-www:/var/www/certbot # <--- BARU: Folder Verifikasi
      - certbot-conf:/etc/letsencrypt # <--- BARU: Tempat Sertifikat disimpan
    depends_on:
      - app
    networks:
      - belajarki-network

  # --- SERVICE BARU ---
  certbot:
    image: certbot/certbot
    container_name: belajarki-certbot
    volumes:
      - certbot-www:/var/www/certbot
      - certbot-conf:/etc/letsencrypt
    networks:
      - belajarki-network

networks:
  belajarki-network:
    driver: bridge

# --- VOLUME BARU ---
volumes:
  web-static:
  certbot-www:
  certbot-conf:
